cache:
  paths:
before_script:
  - "cd $CI_PROJECT_DIR"
  - "git fetch"
  - "git checkout $CI_COMMIT_SHA"
  - "git status"
tests_and_benchmark:
  script:
    - "npm install --ignore-scripts"
    - "npm test"
  only:
    refs:
      - merge_requests
      - master
      - develop
      - web
      - niry_api_improvments_20191125
